---
load: ""
kind: pipeline
name: test-amd64

platform:
  arch: amd64

trigger:
  event:
    - push

environment:
  ZIPLINE_URL: http://zipline:3000/

services:
  - name: postgres
    hostname: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres

  - name: zipline
    hostname: zipline
    image: ghcr.io/diced/zipline:3.7.1
    environment:
      DEBUG: true
      CORE_PORT: 3000
      CORE_RETURN_HTTPS: false
      CORE_SECRET: H8Y9lSs48w3HwOgFfpaF0G
      CORE_DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    depends_on:
      - postgres

steps:
  - name: test-3.11
    image: python:3.11
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - flake8 zipline.py
      - python3 setup.py install
      - while ! curl --silent $${ZIPLINE_URL}; do sleep 1; done
      - export ZIPLINE_TOKEN=$(python3 get_test_token.py)
      - zipline zipline.py

  - name: test-3.10
    image: python:3.10
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - flake8 zipline.py
      - python3 setup.py install
      - while ! curl --silent $${ZIPLINE_URL}; do sleep 1; done
      - export ZIPLINE_TOKEN=$(python3 get_test_token.py)
      - zipline zipline.py

  - name: test-3.9
    image: python:3.9
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - flake8 zipline.py
      - python3 setup.py install
      - while ! curl --silent $${ZIPLINE_URL}; do sleep 1; done
      - export ZIPLINE_TOKEN=$(python3 get_test_token.py)
      - zipline zipline.py

  - name: test-3.8
    image: python:3.8
    depends_on:
      - zipline
    commands:
      - python3 -m pip install -r requirements.txt
      - flake8 zipline.py
      - python3 setup.py install
      - while ! curl --silent $${ZIPLINE_URL}; do sleep 1; done
      - export ZIPLINE_TOKEN=$(python3 get_test_token.py)
      - zipline zipline.py
