name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]
    paths-ignore:
      - ".gitignore"
      - "pyproject.toml"
      - "requirements.txt"

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  if: ${{ always() }}
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Setup Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install"
        id: install
        run: |
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt
          python -m pip install -e .

      - name: "Flake8"
        if: ${{ always() }}
        run: |
          flake8 zipline.py

      - name: "Ruff"
        if: ${{ always() }}
        uses: astral-sh/ruff-action@v3

      #- name: "Black"
      #  if: ${{ always() }}
      #  uses: psf/black@stable

      #- name: "Isort"
      #  if: ${{ always() }}
      #  uses: isort/isort-action@v1

      #- name: "Mypy"
      #  if: ${{ always() }}
      #  run: |
      #    mypy src

      #- name: "Prettier"
      #  if: ${{ always() }}
      #  run: |
      #    npm install prettier
      #    npx prettier --check .

      #- name: "Coverage"
      #  if: ${{ always() }}
      #  id: coverage
      #  run: |
      #    coverage run -m pytest
      #    coverage xml
      #    coverage report -m

      #- name: "Codecov"
      #  if: ${{ always() && steps.coverage.outcome == 'success' }}
      #  uses: codecov/codecov-action@v5
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}

      #- name: "SonarQube"
      #  uses: SonarSource/sonarqube-scan-action@v4
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
